/*
 * This source file was generated by the Gradle 'init' task
 */
package elevator;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Elevator elevator = new Elevator();
		/**
		 * Thread for starting the elevator
		 */
		Thread t2 = new Thread(elevator::run);
		t2.start();

        try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	

		Request request1 = new Request(0,5);

        elevator.addJob(request1);


		elevator.addJob(new Request(6,7));
		elevator.addJob(new Request(6,1));

        try {
			Thread.sleep(10000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

// Taking user input for elevator request
Scanner scanner = new Scanner(System.in);
while (true) {
	System.out.print("\n\nEnter source floor: ");
	int sourceFloor = scanner.nextInt();

	System.out.print("Enter destination floor: ");
	int destinationFloor = scanner.nextInt();

	

	
	Request request = new Request(sourceFloor, destinationFloor);
	elevator.addJob(request);
}

    }
}
